export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const SELECT_EVENTS_SUCCESS = 'SELECT_EVENT_SUCCESS';

export const SELECT_TOWN = 'SELECT_TOWN';
export const FETCH_TOWNS_SUCCESS = 'FETCH_TOWNS_SUCCESS';

export const FETCH_STOPS_SUCCESS = 'FETCH_STOPS_SUCCESS';

export const FETCH_STORES_SUCCESS = 'FETCH_STORES_SUCCESS';